Description
12/6/18   

   pf-claims-service_develop-sri_15

12/3/18  This is a copy of parameterized ClaimsApiOnly
		 The plan here is to take the renameReport Batch file code and
         put it in a post job task.
		 There may be additional arguments passed to me, build TAG,etc.


11/29/18  this is a copy of ClaimsOnly
          this is for the purpose of developing pass in paramaeter to identify test on DIT or test on MOT

11/28/18 Making sure we are checking for zero ( a Pass )
		 Adding the check for repo directory or Fail ( Exit 2 )
----------------------------------------------------------------
11/27/18 Newly copied from test_job_pipeline_ClaimsAPI
	This will be only the Claims API and none of the others MicroServiceAPIs.
	This will report to R:\RESTApi\Regress__Claims   (2 unserscores )
-------------------------------------------------------------------------

11/9/18 this is copied from test_job_pipeline_ESS mid development  ny


/***********************************************************************
/* StringParameter #1 === testServer
/* 12/7/18 Dev Ops request We call this variable ENVIRONMENT
/* And that the passed values will be DEV, DIT, MOT, MOT3
/* All uppercase  package.json Done
/* ======================================================
/* String value passed shall be in 
/* the range "dev ,dit", "mot", "mot3"  
/* and no other value
/* 
/* Should be called ENVIRONMENT
/* *************************************************************************/

/***********************************************************************
/* StringParameter #2 === JENKINS_TAG
/* 12/7/18   
/* We are changeing BUILD_NUMBER  to JENKINS_TAG
/* 
/* 12/10/18 the Text file that I will make will be
/* BUILD_TAG_NUM.txt
/* 
/* This is the correct format and content of 15th build that 
/* Harsha will be passing to me later.
/* the last two chars will incriment to 3 digits then 4, etc.
/* 
/* pf-claims-service_develop-sri_15
/* *************************************************************************/


/***********************************************************************
/* StringParameter #3 === SERVICE
/* 
/* name of the application where the test is being run against
/* *************************************************************************/


1)     Execute Windows batch Command
RD /S /Q C:\jenkins\slave_home\workspace\testJob_params_ClaimsApi_AddedArgs


2)   Execute Windows batch Command
:FileBegin
@echo off

REM **************************************************************************************************
REM  11/30/18 work that I think needs doing.
REM  chedk for resutls.json post execution.  No file === no execution at all.

REM =================================================================
REM  # Set Parameters
REM 11/27/18 ClaimsApiOnly Job

REM reminder  !!!!  none of the log file that redirect into dd-cx-testApi will work until after the clone !!!!


      for /f "tokens=2-8 delims=/:. " %%A in ("%date%:%time%: =0%%") do set "TIMESTAMP=%%C%%A%%B-%%D%%E"

     set this_Project_Directory=testJob_params_ClaimsApi_AddedArgs

     set cxReportsStorage=\\SACAPPSEID01\CX_Rpt_Root

     set testAutomationInitiatedRecord=testAutomationJobs_ExecutionRecord.txt

     set testLaunchCapture=%cxReportsStorage%\%testAutomationInitiatedRecord%

     set workspacePath=c:\jenkins\slave_home\workspace

     set repo=dd-cx-testApi

     set logFile=API_Build_Initiated__LOG.txt

     set debugFile=API_DebugTest__LOG.txt

     set pathToRepo=%workspacePath%\%this_Project_Directory%\%repo%

     set loggingDest=%workspacePath%\%this_Project_Directory%\%repo%\%logFile%

     set loggingDebug=%workspacePath%\%this_Project_Directory%\%repo%\%debugFile%

REM =================================================================
REM # Special variable for publication

     set serverAndPathURL=http://sacappseid01:8080/RESTApi/ClaimsTagReports/%JENKINS_TAG%.html



REM =================================================================
REM #  add that elusive variable that makes readyWait work along with other local additions

     set PATH=%PATH%;C:\jenkins\slave_home\workspace\%this_Project_Directory%\%repo%\node_modules\.bin;c:\bin




REM =================================================================
REM # The following is a HACK !!!!!  
REM # I've had to put it in because there is soooooo much problem with GIT dropping its knowledge of who I am.
REM 1/10/19 tesing the removal of set GIT_SSL_NO_VERIFY=true
  REM   set GIT_SSL_NO_VERIFY=true

REM   call git clone -b dev https://ca34081:Welcome!!4@rc-lx842.ut.dentegra.lab/DEVPROJECTS/dd-cx-testApi.git  
     
     call git clone -b dev https://ca34081:Welcome!!5@rc-lx842.ut.dentegra.lab/DEVPROJECTS/dd-cx-testApi.git  



REM =================================================================
REM # The following is necessary to confirm the git clone happened & if not exit error code 2

if exist C:\jenkins\slave_home\workspace\%this_Project_Directory%\dd-cx-testApi\package.json (
  REM  Special do nothing operation
    ) else (
     echo %TIMESTAMP% Huston we've got a problem >> %workspacePath%\specialCloneFailureLoggingFile.txt 2>&1
     echo %TIMESTAMP% We didn't find %pathToRepo%  >>  %workspacePath%\specialCloneFailureLoggingFile.txt 2>&1
     echo %TIMESTAMP% We are exiting with exit_2   >>  %workspacePath%\specialCloneFailureLoggingFile.txt 2>&1
     echo %TIMESTAMP% -------------------------------------------------------------------------------------------------------------------------------- >>  %workspacePath%\specialCloneFailureLoggingFile.txt 2>&1
     exit 2
)


REM =================================================================
REM # The following is necessary to confirm the variables were passed & if not exit error code 2

cd  C:\jenkins\slave_home\workspace\%this_Project_Directory%\%repo%
set testVarSize=1

if [%testServer%] == [] (
	Echo Failure in size of  testServer Environment Variable.  EXITING_1 NOW >> %loggingDebug% 2>&1
        Echo The Envar testServer was found to be NULL >> %loggingDebug% 2>&1
        goto Exit_1
) ELSE (
       Echo "testServer environment variable passed the null value test [ ] "  >> %loggingDest% 2>&1
       Echo The value of the --testServer--  variable  is %testServer%  >> %loggingDest% 2>&1
       Echo Continue and check the Build Tag - number Environment Variable  >> %loggingDest% 2>&1
)

:CheckJenkins_Tag


if [%JENKINS_TAG%] == [] (
	Echo Failure in size of  Jenkins Build Tag - number Environment Variable.  EXITING_1 NOW >> %loggingDebug% 2>&1
        Echo The Envar JENKINS TAG was found to be NULL >> %loggingDebug% 2>&1    
        goto Exit_1
) ELSE (
       Echo "Jenkins Build Tag - number environment variable passed the null value test [ ] "  >> %loggingDest% 2>&1
       Echo The value of the --JENKINS_TAG--  variable  is %JENKINS_TAG%  >> %loggingDest% 2>&1
       Echo %JENKINS_TAG%   >> BUILD_TAG_NUM.txt  2>&1
)


if [%SERVICE%] == [] (
	Echo Failure in size of  SERVICE Environment Variable.  EXITING_1 NOW >> %loggingDebug% 2>&1
        Echo The Envar SERVICE was found to be NULL >> %loggingDebug% 2>&1
        goto Exit_1
) ELSE (
       Echo "SERVICE environment variable passed the null value test [ ] "  >> %loggingDest% 2>&1
       Echo The value of the --SERVICE-- variable  is %SERVICE%  >> %loggingDest% 2>&1
       goto InputVarSuccess
)
:InputVarSuccess


REM 
REM
REM
REM =============================================================
REM I need to check and make sure the testServer Var is in the range
REM  [ dev  dit   mot   mot3 ]  and exit 1  reporting failure  

REM =================================================================
REM #  Debugging step 

     echo %TIMESTAMP% First Opportunity to log to this file.  All Input Params passed, No Exit_1 goto's >> %loggingDebug% 2>&1
    


REM REM =================================================================
REM REM #  start logging to a file in the repo directory now that cloning has finished




REM REM =================================================================
REM REM #  record success to this point.



REM =================================================================
REM # Move to the node_modules directory and unpack the zip file

   call cd c:\jenkins\slave_home\workspace\%this_Project_Directory%\%repo%\node_modules  >> %loggingDest% 2>&1
   call "c:\Program Files\7-Zip\7z.exe" x node_modules.zip   >> %loggingDest% 2>&1




REM =================================================================
REM #  Debugging step 
     echo %TIMESTAMP% Second Opportunity to log to this file.  Node_modules just unzipped >> %loggingDebug% 2>&1




REM ================================================================= 
REM  Move to the Repository Root directory in preparation to start
     cd c:\jenkins\slave_home\workspace\%this_Project_Directory%\%repo%


REM =================================================================
REM 
REM # >                               START TEST                                        <
REM
REM 
REM ***************************************************************
REM  Comment: enrollClaimApi<testServer>  changed to enrollApi<testServer>
REM  Changed 12/4/18  via  Raghu and team PR merge 
REM    cmd /c npm run enrollClaimApidit -- --suite=devAuto3  >> %loggingDest% 2>&1


REM    cmd /c npm run enrollApi%testServer% -- --suite=devAuto3  >> %loggingDest% 2>&1
            cmd /c npm run enrollApi%testServer% -- --suite=claimsAPI  >> %loggingDest% 2>&1


REM =================================================================
REM #  Debugging step 
     echo %TIMESTAMP% Third Opportunity to log to this file. Just ran enrollAPI%testServer suite claimsAPI >> %loggingDebug% 2>&1




REM  =================================================================
REM #    >                     Copy, Rename  & Move  Report                          <


call copy dashboardNGTA.html %JENKINS_TAG%.html

cmd /c curl -k -u develop:AP4BU7ZARCg3Kzdp -X PUT "https://jfrogbuild.deltads.ent/artifactory/delta-bin-local-dev-cx/reports/%JENKINS_TAG%.html" -T %JENKINS_TAG%.html

call rename_Dashboard_Rpt.bat 

call rename_Dashboard_Rpt.bat moveTagFile %JENKINS_TAG%.html

Echo ....
Echo ..
Echo .

Echo please review %serverAndPathURL%


REM =================================================================
REM # Evaluate results.json :  Looking for passes === false

echo %TIMESTAMP% Fourth Opportunity starting to look at result.json.  Just Renamed the Report _ or Not >> %loggingDebug% 2>&1

     cd c:\jenkins\slave_home\workspace\%this_Project_Directory%\%repo%

     grep "\"passed\": false," results.json > testFileForFailureOutput.txt



REM =================================================================
REM #  Debugging step
     echo %TIMESTAMP% Fifth Opportunity after GREP for passed : false  >> %loggingDebug% 2>&1

     set size=0
     set testSize=0

     for /f %%i in ("testFileForFailureOutput.txt") do set size=%%~zi


REM =================================================================
REM #  Debugging step
     echo %TIMESTAMP% - Debugging Step
     echo Sixth Opportunity after setting the two size-and-testSize variables  >> %loggingDebug% 2>&1
     echo Test Variables are: %size%  and  %testSize% >> %loggingDebug% 2>&1

     if %size% gtr %testSize% ( 
       set GTR_TestStringOut=TestFileForFailureOutput_was_GREATER_than_%TestSize%_We found failure  >> %loggingDebug% 2>&1
       type testFileForFailureOutput.txt   >> %loggingDebug% 2>&1
       goto Exit_1
     ) ELSE (
      echo "TestFileForFailureOutput was found to be Less than %size% :  No Failure Found   >> %loggingDebug% 2>&1
       type testFileForFailureOutput.txt   >> %loggingDebug% 2>&1
       goto Exit_0
 )



:Exit_1
echo %GTR_TestStringOut%  >> %loggingDebug% 2>&1
echo Taking the Exit One (1)  Route >> %loggingDebug%
 Exit 1

:Exit_0
echo Taking the Exit Zero (0) Route >> %loggingDebug% 
Exit /B 0


:Exit_Wow
 echo Taking the Exit One(1) No Arguments found :(((  >> %loggingDebug% 
 Exit 1




:FileEnd